apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: highscore
  name: highscore
  namespace: yogender027mae-dev
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: highscore:latest
  runPolicy: Serial
  source:
    contextDir: highscore-game
    git:
      uri: https://github.com/NautiluX/s3e
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: alpine:latest
        namespace: yogender027mae-dev
    type: Docker
  successfulBuildsHistoryLimit: 5
